### ISSUE TITLE
Chat room

### ISSUE THREAD

**Issue by heygambo** [AwesomeCities/org#1]
hey @mischah @lfuelling 

I used to have a slack channel but only 1-2 people joined and nobody ever wrote.
The links to slack are still there but they don't work since I gave up the domain.

In addition to that I always thought slack might no be the best option due to the history limit and business use case.

There are 4 things that come to mind that we could do.

1) remove the link
2) move to gitter
3) move to riot.im
4) continue to use slack

Do you have any preference? Do you think it's good to have a chat room?

Best, Gambo

**Comment by lfuelling** [comment]
I'd prefer using Gitter, since anyone who has a GitHub account can join the chat.

(Never used riot)
